title:             Soohyun's Clean Blog
email:             happykimoob@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "https://soohyunii.github.io/"
theme:             jekyll-theme-awesome

# Social Profiles
twitter_username:  SBootstrap
github_username:   soohyunii
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
